SET NAMES UTF8;
DROP DATABASE IF EXISTS cfdmf;
CREATE DATABASE cfdmf SET UTF8;
USE cfdmf;
CREATE TABLE cfdmf_user(
	uid INT PRIMARY KEY AUTO INCREMENT,
	uname VARCHAR(16),
	phone VARCHAR(11),
	upwd VARCHAR(64)
)
